% uncomment 3 following lines to update dynaload csv descriptor
% -------------------------------------------------------------
% dynaload = 'global_oceansites';
% f = us191.dynaload(strcat(dynaload, '.xls'));
% write(f, strcat(dynaload, '.csv'));

% test pour chargement base
us191.roscop2oceansites('type','profile','argo','test-ctd_ctd.nc',...
  'cycle_mesure','TEST-CTD2',...
  'parameters',{'TEMP','PSAL','DENS','SVEL','DOX2'},'levels',{'PRES','DEPH'},...
  'platform_name','ANTEA','platform_code','FNUR','wmo_platform_code','35A8',...
  'type_instrument','SBE911','number_instrument','91781',...
  'time_coverage_start','2009-06-13T09:00:00Z',...
  'time_coverage_end','2009-06-23T00:00:00Z',...
  'pi_name','Bernard Bourles','author','Jacques Grelet',...
  'project_name','PIRATA');

% CTD - PIRATA-BR1
% ----------------
us191.roscop2oceansites('type','profile','argo','profile/pirata-br1_ctd.nc',...
  'cycle_mesure','PIRATA-BR1',...
  'parameters',{'TEMP','PSAL','DENS','SVEL'},'levels',{'PRES','DEPH'},...
  'platform_name','ANTARES','platform_code','NPEJ','wmo_platform_code','32A7',...
  'type_instrument','SBE911','number_instrument','91781',...
  'time_coverage_start','1998-01-20T08:00:00Z',...
  'time_coverage_end','1998-01_31T08:00:00Z',...
  'pi_name','Joao A. Lorenzzetti','author','Jacques Grelet',...
  'project_name','PIRATA');
us191.roscop2oceansites('type','profile','argo','profile/pirata-fr5_ctd.nc',...
  'cycle_mesure','PIRATA-FR5',...
  'parameters',{'TEMP','PSAL','DENS','SVEL'},'levels',{'PRES','DEPH'},...
  'platform_name','ANTEA','platform_code','FNUR','wmo_platform_code','35A8',...
  'type_instrument','SBE911+','number_instrument','11P928',...
  'time_coverage_start','1999-10-25T08:00:00Z',...
  'time_coverage_end','1999-11-08T08:00:00Z',...
  'pi_name','Bernard Bourles','author','Jacques Grelet',...
  'project_name','PIRATA');

% PIRATA-FR19
% ----------------
% CTD
us191.roscop2oceansites('type','profile','argo','profile/pirata-fr19_ctd.nc',...
  'cycle_mesure','PIRATA-FR19',...
  'platform_name','ANTEA','platform_code','FNUR','type_instrument','SBE911+',...
  'parameters',{'TEMP','PSAL','DOX2','DENS','SVEL'},'levels',{'PRES','DEPH'},...
  'number_instrument','11P928','wmo_platform_code','35A8',...
  'time_coverage_start','2009-06-13T09:00:00Z',...
  'time_coverage_end','2009-07-23T08:00:00Z',...
  'pi_name','Bernard Bourles','author','Jacques Grelet',...
  'project_name','PIRATA');
% XBT
us191.roscop2oceansites('type','profile','argo','profile/pirata-fr19_xbt.nc',...
  'cycle_mesure','PIRATA-FR19',...
  'platform_name','ANTEA','platform_code','FNUR','type_instrument','MK21',...
  'parameters',{'TEMP','PSAL','DENS'},'levels',{'PRES','DEPH'},...
  'number_instrument','N/A','wmo_platform_code','35A8',...
  'time_coverage_start','2009-06-13T09:00:00Z',...
  'time_coverage_end','2009-07-23T08:00:00Z',...
  'pi_name','Bernard Bourles','author','Jacques Grelet',...
  'project_name','PIRATA');